### ISSUE TITLE
Can't send message to group

### ISSUE THREAD

**Issue by Noorquacker** [mh-g/python-signal-cli#2]
I've been trying for days to figure out how group chats work over dbus
In my Python code, I start off with something just like `base = 'SomeBase64Here'` as a starting point and then converting that for what `signal.sendMessage()` needs in order to send to a group chat.

I tried to use something like `id = [hex(i) for i in base64.b64decode(base)]` but that didn't work, along with a bunch of other methods which I kept erasing. Even the raw output from `hexdump` put into each own byte, with or without 0x in front, still resulted in failure
Every time I do it, I get this:
```
Traceback (most recent call last):
  File "helpme.py", line 39, in <module>
    signal.sendMessage('Test message', [], idthing)
  File "/usr/local/lib/python3.8/dist-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.asamk.Signal.Error.Failure: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found (36)
```
How would I convert the base64 of a group chat ID to something that signal-cli on dbus would accept? Or even the raw list of ints given from dbus when a message is received?

**Comment by mh-g** [comment]
I use the following code:

signal.sendGroupMessage(data, [], [0x89, 0x55,   ... ,   0x1e, 0xad])

where 0x89, 0x55,   ... ,   0x1e, 0xad are the bytes from base64.b64decode ("...") of the groupId taken from groupStore of the configuration file from ~/.config/signal/data/<your-phone-number>, e.g.:

b'\x89U   ...     \x1e\xad'

**Comment by Noorquacker** [comment]
Ah, nice, one of my only GitHub issues ever opened turns out to me messing up.
I was using `signal.sendMessage` instead of `signal.sendGroupMessage` the entire time...for multiple days
Thank you for helping, though. I didn't notice until you said it in that response.
