### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by bsddemon** [mh-g/python-signal-cli#4]
I used the stdin-to-user.py example.

When I run it, I get the following error: 
signal.sendMessage(data, [], 'xxx')
AttributeError: '<CompositeObject>' object has no attribute 'sendMessage'

**Comment by kmille** [comment]
you need to add your number in the proper format:
```python
signal = bus.get('org.asamk.Signal', object_path='/org/asamk/Signal/_4915474133374)
```
